# Generated by Django 4.1.4 on 2023-03-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_course_student_teacher_delete_teachermodel_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table='schedule_teacher',
        ),
    ]
